spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/jwt_security
    username: david
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  tutorial:
    secret: 5367566B59703373367638792F423F4528482B4D6251655468576D5A71347437